### ISSUE TITLE
gdal version for writing raster to GeoPackage?

### ISSUE THREAD

**Issue by rkrug** [rkrug/rGeoPackage#6]
@mdsumner Which version of gdal is required when writing raster to GeoPackage files? I am using 

```
> library(rgdal)
Loading required package: sp
rgdal: version: 1.1-10, (SVN revision 622)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 1.11.3, released 2015/09/16
 Path to GDAL shared files: /usr/local/Cellar/gdal/1.11.3_1/share/gdal
 Loaded PROJ.4 runtime: Rel. 4.9.2, 08 September 2015, [PJ_VERSION: 492]
 Path to PROJ.4 shared files: (autodetected)
 Linking to sp version: 1.2-3 
```

but I have no GPKP raster driver - only vector?

**Comment by mdsumner** [comment]
It is present, just not listed. Might be fixed now. https://gist.github.com/mdsumner/cc9b29692c450fd182cfbf46b85c5365

**Comment by rkrug** [comment]
My fault - I am still using gdal 1.11.3 with rgdal. Trying to use gdal 2.1 now in rgdal.

My gdal 1.11.3 does not contain the GPKG driver for raster.
