### ISSUE TITLE
multiple layers in a GPKG file

### ISSUE THREAD

**Issue by mdsumner** [rkrug/rGeoPackage#8]
This is a place holder for something I want to explore. 

It seems you can't create more than one layer with writeOGR. 

Needs an example 

(GeoPackage can contain vector and raster layers, and multiple of each apparently. )

**Comment by mdsumner** [comment]
Is GPKG inherently multi-topological, or would it have to treat points and lines as separate layers?

**Comment by rkrug** [comment]
But it seems you can add a second layer by using `ogr2ogr`:

On [http://gis.stackexchange.com/questions/174953/how-to-add-another-layer-to-geopackage-in-qgis](http://gis.stackexchange.com/questions/174953/how-to-add-another-layer-to-geopackage-in-qgis) the example is given:

`ogr2ogr -f "GPKG" out.gpkg in.[shp|gpkg] -append -update`

But I haven't tried it and have just seen it.

**Comment by rkrug** [comment]
I have just pushed some sample data which contains different layers with different topologies. The `gdal_sample.gpkg` contais for example:

```
[1] "point2d"           "linestring2d"      "polygon2d"         "multipoint2d"     
 [5] "multilinestring2d" "multipolygon2d"    "geomcollection2d"  "geometry2d"       
 [9] "point3d"           "linestring3d"      "polygon3d"         "multipoint3d"     
[13] "multilinestring3d" "multipolygon3d"    "geomcollection3d"  "geometry3d"  
```

See commit 7f80d55f

They can be read by using e.g. 

```
fn <- system.file("geopackage_sample_data", "gdal_sample.gpkg", package= "rGeoPackage")
x <- geopackage(fn, "polygon2d", verbose = TRUE)
```

But I haven't tried to create one or add layers to it.

**Comment by rkrug** [comment]
you can create a multy-layer gpkg containing all `file_....gpkg` files by using the following code:

```
05:34:32 {master} ~/Documents/Projects/R-Packages/rGeoPackage/inst/extdata$ ogr2ogr -f "GPKG" all.gpkg file_point.gpkg
05:34:41 {master} ~/Documents/Projects/R-Packages/rGeoPackage/inst/extdata$ ogr2ogr -update -append -f "GPKG" all.gpkg file_line.gpkg
05:35:04 {master} ~/Documents/Projects/R-Packages/rGeoPackage/inst/extdata$ ogr2ogr -update -append -f "GPKG" all.gpkg file_poly.gpkg
05:35:11 {master} ~/Documents/Projects/R-Packages/rGeoPackage/inst/extdata$ ogrinfo all.gpkg
INFO: Open of `all.gpkg'
      using driver `GPKG' successful.
1: pointlayer (Point)
2: linelayer (Multi Line String)
3: polylayer (Multi Polygon)
```

 have added this to the file `file.r` in commit ee4215b
