### ISSUE TITLE
Function to aid in writing a reproducible GPKG file

### ISSUE THREAD

**Issue by florisvdh** [rkrug/rGeoPackage#9]
Just wondering what is the maintenance status of the package?

I've [been exploring](https://github.com/r-spatial/sf/issues/1618#issuecomment-791622559) a function to make writing GeoPackages binary reproducible. Although I now wrote it inside a fork of **sf**, it's just a helper function, independent of specific package infrastructure. Had been thinking of distributing this function standalone, but just met **rGeoPackage**, where it (maybe) could fit as well. I guess this mainly depends on future and aims of the package.

**Comment by florisvdh** [comment]
@rkrug Can you let me know your opinion? Currently I consider making a small R-package `rgeopackage` (for CRAN), with miscellaneous tools which are (currently) not provided by core spatial packages or by GDAL.

Two functions which I think are ready more or less:

- `preset_timestamp()`: before creating GeoPackages; pass timestamp to GDAL
- `amend_timestamp()`: overwrite timestamp in existing GeoPackages

**Comment by rkrug** [comment]
Sorry for not replying earlier.

Development has stopped as I moved into other fields of work. Please feel free to do take the name and submit it to CRAN. If you want to, I can transfer the repository to you or just post a note here that this repo is not used anymore.

Let me know what you prefer.

Cheers,

Rainer

**Comment by florisvdh** [comment]
Thank you Rainer.

For me to maintain, in se it would be easier to start anew.

But first: would you like to have the `rgdal`-based functions still included? If so, then that's OK and I think then it's better to transfer the repository indeed. Personally I have some doubt whether the functions _currently_ still add a lot compared to functionality in `sf` (e.g. `st_read()` also gives a message when taking first layer automatically from multiple ones). But I am interested to know your preference on this!

**Comment by rkrug** [comment]
Absolutely no need to include it. I will than change the README and add a link to your package, which would be taking over from this idea (it really was not much more).

Cheers,

Rainer

**Comment by florisvdh** [comment]
OK Rainer, agreed, and thank you for being so supportive. When the new `rgeopackage` is on GitHub, I'll post its link here so that you can add it in README. And of course the package will be open to contributions.

**Comment by florisvdh** [comment]
@rkrug a new `rgeopackage` is now available from GitHub: https://github.com/florisvdh/rgeopackage. Can you reference it in your `README`? It's possible that it will be transferred to an organisation (mine or another) in the future - in that case I'll let you know the changed URL.

**Comment by rkrug** [comment]
Done. Thanks a lot @florisvdh.

**Comment by florisvdh** [comment]
Thanks @rkrug !
